# Generated by Django 4.0.4 on 2022-05-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ('-hospital',)},
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='hospital_name',
            new_name='hospital',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='web',
            field=models.URLField(blank=True, verbose_name='Website of Hospital'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('details', models.TextField(blank=True, verbose_name='Work Experience')),
                ('departament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.departments')),
            ],
        ),
    ]
