# Generated by Django 4.0.4 on 2022-05-12 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_depaments_hospitals_departament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={},
        ),
        migrations.RemoveField(
            model_name='departments',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.departments'),
        ),
        migrations.DeleteModel(
            name='Depaments',
        ),
    ]
