# Generated by Django 4.0.4 on 2022-05-12 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='doctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.doctor'),
        ),
    ]
